### ISSUE TITLE
What's the paper of this project?

### ISSUE THREAD

**Issue by kingbase** [nezezime/bnAnomaly#1]
It seems this project is based on the paper `Anomaly Detection and Attribution Using Bayesian Networks`, am I right?
Also seems that this project is still work in progress?
Thanks.

**Comment by nezezime** [comment]
Hello kingbase, this project is part of the work that I performed for my masters thesis, I added the accompanying paper to the repository so feel free to take a look at it.
You are right that this is still work in progress but I am now working on a different project so updates will depend on my free time. Therefore, you may consider it more as an unoptimized demonstration of what can be done with these tools and the data.

**Comment by kingbase** [comment]
Thanks for the reply and I'll read through the paper, great work
