### ISSUE TITLE
How to use bnAnomaly

### ISSUE THREAD

**Issue by MabroukAhmed** [nezezime/bnAnomaly#2]
I'm trying to use your code inside my anomaly detection project. I build a Bayesian network using bnlearn package. I fit CPTs through bn.fit() function. However, I don't understand which function (in your C++ code) should I use to send my built BN (as a parameters) and use it to compute log likelihood?

In other word, how can I initialize cpp_loglik with my bn.fit object?

a = tabu(asia)
bn = bn.fit(a, asia)
cpp_loglik(bn)?

many thanks

**Comment by nezezime** [comment]
Hi Mabrouk,
glad to hear you are working on anomaly detection. I have added a simple R script to this repository which may help you to initialize log likelihood. So, after importing the script, the flow of your code should look something like this:

source("r_log_lik.R")
a = tabu(asia)
bn_fitted = bn.fit(a, asia)
cpp.init(bn_fitted, "e") # second argument is the logarithm base
cpp_logLik(test_data)

Please note that I have not implemented missing data handling, so test_data should contain complete samples only. Hope this helps.
